### PR TITLE
version 0.3.7

### PR DESCRIPTION
**Pull request by ThierryO**

### CODE REVIEW

**Comment by wlangera** [comment]
I still have some issues:

**1. multiple zenodo communities**

I cannot set multiple zenodo communities in the organisation.yml and DESCRIPTION.

```
checklist::update_citation()
#> Error in initialize(...) : `community` must be a string
```

**2. adding info@inbo.be as email in DESCRIPTION**

I cannot set info@inbo.be as email for "Research Institute for Nature and Forest (INBO)" in DESCRIPTION.
Still same warnings as in #129.
Maybe a clash with organisation.yml?

**3. copyright holder differs from funder**

After `checklist::check_package()`.
I can allow notes on this when I have a different copyrightholder and funder in DESCRIPTION.

```
#> `Research Institute for Nature and Forest (INBO)` must be listed as copyright holder and funder and use `NA_character_` as email.
```

But I get an error if I also adjust this in the organisation.yml.

```
Error in check_authors(read_organisation(x$get_path), this_desc = this_desc) : 
  TO DO: handle funder not equal to rightsholder
```

**4. GitHub action has problem with CITATION.cff**

[This branch](https://github.com/b-cubed-eu/gcube/tree/add-checks) has no errors (only the shortcommings from 1-3 above).
But on GitHub I get this warning.

```
 /github/workspace/check/CITATION.cff is modified. Run `checklist::update_citation()` locally. Please commit changes.
```

Running `checklist::update_citation()` does not change anything.

**Comment by wlangera** [comment]
I created a separate branch [here](https://github.com/b-cubed-eu/gcube/tree/checklist-bugs) with the problems mentioned above.

**Comment by wlangera** [comment]
This time, I created a project with for a different organisation. Here are my issues:

**1. Not possible to set 2 zenodo communities (?)**
I have added an organisation.yml which enables me to use the b3 community instead of the inbo community.
Yet, I want both. How can I do this?

In my README.md `<!-- community: b3; inbo -->` does not work:

```
Errors found while parsing citation meta data

------------------------------------------------------------------------------------------------------------
missing required Zenodo community `b3`
```

**2. Use MIT licence**

I want the MIT licence: `usethis::use_mit_license(copyright_holder = "Research Institute for Nature and Forest (INBO)")`.
Even when removing licence checking from checklist.yml, checklist still returns an error because I changed the licence.

```
CITATION: 1 error
------------------------------------------------------------------------------------------------------------
 LICENSE.md doesn't match with CC-BY-4.0 license
```


I created a separate branch [here](https://github.com/b-cubed-eu/comp-unstructured-data/tree/checklist-issues) with the problems mentioned above.

**Comment by ThierryO** [comment]
@hansvancalster Can you look at the MIT license error? You wrote that code. Please improve the error message.

**Comment by wlangera** [comment]
@ThierryO I am not sure this is an error related to the MIT licence or also something bigger.
I get errors from `checklist::check_project()` regarding the license AND folder names even if I remove these from the checklist.yml.

**Comment by hansvancalster** [comment]
@wlangera the repo you point to is not an R package. Checklist currently only allows GPL or MIT license for R packages, but forces CC-BY 4.0 for repos that are not R packages. Ignoring the `license.md` file seems to only have the effect that it is ignored during spell checking (if I look at your `checklist.yml` file)? The tutorial indeed suggests that checking the `LICENSE.md` file can be ignored entirely:

image

which suggests that it could be used as a way to "allow" any other license for repos that are not R packages (with the caveat that checklist will not check it).

@ThierryO the error " LICENSE.md doesn't match with CC-BY-4.0 license" is thrown by the internal function `checklist:::citation_readme()` which is code that you wrote. I only wrote code to allow MIT license in R packages, but this issue is reported from a repo that was probably created by `checklist::create_project()`.

**Comment by ThierryO** [comment]
> **1. Not possible to set 2 zenodo communities (?)** I have added an organisation.yml which enables me to use the b3 community instead of the inbo community. Yet, I want both. How can I do this?
> 
> In my README.md `<!-- community: b3; inbo -->` does not work:

Write it as
```
<!-- community: b3 -->
<!-- community: inbo -->
```

> 
> ```
> Errors found while parsing citation meta data
> 
> ------------------------------------------------------------------------------------------------------------
> missing required Zenodo community `b3`
> ```
> 
> **2. Use MIT licence**
> 
> I want the MIT licence: `usethis::use_mit_license(copyright_holder = "Research Institute for Nature and Forest (INBO)")`. Even when removing licence checking from checklist.yml, checklist still returns an error because I changed the licence.
> 
> ```
> CITATION: 1 error
> ------------------------------------------------------------------------------------------------------------
>  LICENSE.md doesn't match with CC-BY-4.0 license
> ```

As @hansvancalster mentioned you need to use the CC-BY license for projects. Use  the new `checklist::set_license()`.

**Comment by wlangera** [comment]
Thanks @ThierryO for all your work.
I can pass my checks now.

**Review by wlangera — APPROVED** [review]
Thanks. This version works for me for both projects and packages for an external organisation (B-Cubed project).

**Pull request merged**
